<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule;

use MU\AutoLinksModule\Base\AbstractAutoLinksModuleInstaller;
use RuntimeException;

/**
 * Installer implementation class.
 */
class AutoLinksModuleInstaller extends AbstractAutoLinksModuleInstaller
{
    /**
     * Upgrade the MUAutoLinksModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
         $logger = $this->container->get('logger');
         
         // Upgrade dependent on old version number
         switch ($oldVersion) {
         case '1.0.0':

         // update the database schema
         try {
         $this->schemaTool->update($this->listEntityClasses());
         } catch (\Exception $exception) {
         $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
         $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'MUAutoLinksModule', 'errorMessage' => $exception->getMessage()]);
         
         return false;
         }
         case '1.0.1':
         // for later use
         }
        
        // update successful
        return true;
    }
    // feel free to extend the installer here
}
