<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Entity\Repository;

use MU\AutoLinksModule\Entity\Repository\Base\AbstractAutoLinkRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for auto link entities.
 */
class AutoLinkRepository extends AbstractAutoLinkRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
}
