services:
    mu_autolinks_module.link_container:
        class: MU\AutoLinksModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@mu_autolinks_module.controller_helper"
            - "@mu_autolinks_module.permission_helper"
        tags: ['zikula.link_container']
    mu_autolinks_module.menu_builder:
        class: MU\AutoLinksModule\Menu\MenuBuilder
        arguments:
            - "@translator.default"
            - "@knp_menu.factory"
            - "@event_dispatcher"
            - "@request_stack"
            - "@mu_autolinks_module.permission_helper"
            - "@zikula_users_module.current_user"
        tags:
            - { name: knp_menu.menu_builder, method: createItemActionsMenu, alias: mUAutoLinksMenuItemActions }
