services:
    # Twig extension
    mu_autolinks_module.twig_extension:
        class: MU\AutoLinksModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@mu_autolinks_module.entity_display_helper"
            - "@mu_autolinks_module.workflow_helper"
            - "@mu_autolinks_module.listentries_helper"
        public: false
        tags: ['twig.extension']
