services:
    # Custom validators
    mu_autolinks_module.validator.list_entry.validator:
        class: MU\AutoLinksModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_autolinks_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_autolinks_module.validator.list_entry.validator }
