<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Form\Type\QuickNavigation;

use MU\AutoLinksModule\Form\Type\QuickNavigation\Base\AbstractAutoLinkQuickNavType;

/**
 * Auto link quick navigation form type implementation class.
 */
class AutoLinkQuickNavType extends AbstractAutoLinkQuickNavType
{
    // feel free to extend the base form type class here
}
