<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\AutoLinksModule\Entity\AutoLinkEntity;

/**
 * Event base class for filtering auto link processing.
 */
class AbstractFilterAutoLinkEvent extends Event
{
    /**
     * @var AutoLinkEntity Reference to treated entity instance.
     */
    protected $autoLink;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterAutoLinkEvent constructor.
     *
     * @param AutoLinkEntity $autoLink Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(AutoLinkEntity $autoLink, array $entityChangeSet = [])
    {
        $this->autoLink = $autoLink;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return AutoLinkEntity
     */
    public function getAutoLink()
    {
        return $this->autoLink;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
