<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\HookSubscriber;

use MU\AutoLinksModule\HookSubscriber\Base\AbstractAutoLinkFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class AutoLinkFilterHooksSubscriber extends AbstractAutoLinkFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
