<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Event;

use MU\AutoLinksModule\Event\Base\AbstractFilterAutoLinkEvent;

/**
 * Event implementation class for filtering auto link processing.
 */
class FilterAutoLinkEvent extends AbstractFilterAutoLinkEvent
{
    // feel free to extend the event class here
}
