<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Entity\Factory\Base;

use MU\AutoLinksModule\Entity\AutoLinkEntity;
use MU\AutoLinksModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    /**
     * Initialises a given autoLink instance.
     *
     * @param AutoLinkEntity $entity The newly created entity instance
     *
     * @return AutoLinkEntity The updated entity instance
     */
    public function initAutoLink(AutoLinkEntity $entity)
    {
        return $entity;
    }

}
