<?php
/**
 * AutoLinks.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\AutoLinksModule\Form\Type;

use MU\AutoLinksModule\Form\Type\Base\AbstractAutoLinkType;

/**
 * Auto link editing form type implementation class.
 */
class AutoLinkType extends AbstractAutoLinkType
{
    // feel free to extend the auto link editing form type class here
}
